name: TwiAntiVpn
version: '${version}'
authors:
  - gerolndnr
  - siberanka
website: https://github.com/siberanka
main: com.siberanka.twiantivpn.spigot.ConnectionGuardSpigotPlugin
api-version: 1.13
folia-supported: true
softdepend:
  - LuckPerms
  - Asteroid
  - AsteroidProxy
  - AsteroidSpoofer
  - AsteroidLibs
loadbefore:
  - Sonar
  - SonarBukkit
commands:
  connectionguard:
    name: connectionguard
    description: Retrieve information about connections ingame.
    aliases:
      - cg
